### ISSUE TITLE
only build changed containers

### ISSUE THREAD

**Issue by jgero** [jgero/my-webpage#22]
It would be nice if only the containers/pages that actually were changed since the last build were built again. Maybe have a look at bazel or other build tools for that.

**Comment by jgero** [comment]
Using bazel for this is really hard because svelte and sapper do not really support this. The main problem is, that bazel expects to define the exact amount and name of ouput files, which is not really possible, because sapper hashes the built files. That means the filenames of the output cannot be determined in the preparation phase of the build.

Maybe just thinking very easy and using the bog-standard cache of docker builds, [which is supported by cloud build](https://cloud.google.com/cloud-build/docs/speeding-up-builds#using_a_cached_docker_image) may be the solution.

**Comment by jgero** [comment]
Because the production build is multi-staged and only the final stage gets pushed to the container registry caching is only possible for the last stage. Like someone pointed out in [this StackOverflow answer](https://stackoverflow.com/a/56489130/13360987) the steps in between need to be pushed to the registry as well.

**Comment by jgero** [comment]
[This here](https://stackoverflow.com/questions/52646303/is-it-possible-to-cache-multi-stage-docker-builds) seems to be the only way to currently make caching in multi staged docker builds work.

**Comment by jgero** [comment]
[Here](https://stackoverflow.com/questions/50249644/how-to-cache-multi-stage-docker-build-in-google-cloud-builder) is an example of how it could be done.

**Comment by jgero** [comment]
Completed in e3d40eb7631a45877aeefa02cef432fcd931df51.

**Comment by jgero** [comment]
I just saw a weird jump in cost because of "GCP Storage egress between NA and EU". After a bit of research i realized that cloud build can run on any region and there is no way of stopping it from doing that. This leads to a cloud build running in NA to pull the big intermediate images from EU, causing about 1.3 GB of egress for each build run in NA.

Maybe the caching should be removed again, because build time is not an issue anyways. Also the builds did not really speed up by that much because most part of the build is just installing `node_modules` and it doesn't really matter if i download the `node_modules` from the npm servers again or the image with the already installed modules from my own cache.

**Comment by jgero** [comment]
For future reference: the version with the multistage caching looks like this:

```yaml
# ---------------------------------------------------------------------------------------
# ------------------------------- CLOUDBUILD CONFIG -------------------------------------
# ---------------------------------------------------------------------------------------
# The production version of these sapper apps use a multi staged docker build. To improve
# build times caching is used, but docker currently does not really support caching for
# multi staged docker builds. When building normally only the final image gets cached.
# By incrementally building the steps with targets, tagging the builder steps, pushing
# these intermediate images and using them as cache in the build, caching works for
# such multi staged builds too.
# ---------------------------------------------------------------------------------------
steps:
# ---------------------------------------------------------------------------------------
# --------------------------- BUILD PORTFOLIO IMAGE -------------------------------------
# ---------------------------------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull eu.gcr.io/$PROJECT_ID/portfolio-page-app-builder:latest || true
      docker pull eu.gcr.io/$PROJECT_ID/portfolio-page-runtime-builder:latest || true
      docker pull eu.gcr.io/$PROJECT_ID/portfolio-page:latest || true
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/portfolio-page-app-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/portfolio-page-app-builder:latest \
          -f ./docker/prod.Dockerfile \
          --target app-builder \
          ./portfolio
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/portfolio-page-app-builder:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/portfolio-page-runtime-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/portfolio-page-runtime-builder:latest \
          -f ./docker/prod.Dockerfile \
          --target runtime-builder \
          ./portfolio
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/portfolio-page:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/portfolio-page-app-builder:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/portfolio-page-runtime-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/portfolio-page:latest \
          -f ./docker/prod.Dockerfile \
          ./portfolio
# push the portfolio image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/portfolio-page:latest']
# deploy portfolio image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'portfolio-page'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/portfolio-page:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
# ---------------------------------------------------------------------------------------
# ------------------------------- BUILD SPACE IMAGE -------------------------------------
# ---------------------------------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull eu.gcr.io/$PROJECT_ID/space-page-app-builder:latest || true
      docker pull eu.gcr.io/$PROJECT_ID/space-page-runtime-builder:latest || true
      docker pull eu.gcr.io/$PROJECT_ID/space-page:latest || true
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/space-page-app-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/space-page-app-builder:latest \
          -f ./docker/prod.Dockerfile \
          --target app-builder \
          ./space
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/space-page-app-builder:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/space-page-runtime-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/space-page-runtime-builder:latest \
          -f ./docker/prod.Dockerfile \
          --target runtime-builder \
          ./space
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/space-page:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/space-page-app-builder:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/space-page-runtime-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/space-page:latest \
          -f ./docker/prod.Dockerfile \
          ./space
# push the space image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/space-page:latest']
# deploy space image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'space-page'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/space-page:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
# ---------------------------------------------------------------------------------------
# ----------------------------- BUILD MAIN PAGE IMAGE -----------------------------------
# ---------------------------------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull eu.gcr.io/$PROJECT_ID/main-page-app-builder:latest || true
      docker pull eu.gcr.io/$PROJECT_ID/main-page-runtime-builder:latest || true
      docker pull eu.gcr.io/$PROJECT_ID/main-page:latest || true
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/main-page-app-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/main-page-app-builder:latest \
          -f ./docker/prod.Dockerfile \
          --target app-builder \
          ./main
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/main-page-app-builder:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/main-page-runtime-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/main-page-runtime-builder:latest \
          -f ./docker/prod.Dockerfile \
          --target runtime-builder \
          ./main
      docker build \
          --cache-from eu.gcr.io/$PROJECT_ID/main-page:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/main-page-app-builder:latest \
          --cache-from eu.gcr.io/$PROJECT_ID/main-page-runtime-builder:latest \
          -t eu.gcr.io/$PROJECT_ID/main-page:latest \
          -f ./docker/prod.Dockerfile \
          ./main
# push the main image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/main-page:latest']
# deploy main image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'main-page'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/main-page:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
images:
- 'eu.gcr.io/$PROJECT_ID/portfolio-page:latest'
- 'eu.gcr.io/$PROJECT_ID/portfolio-page-app-builder:latest'
- 'eu.gcr.io/$PROJECT_ID/portfolio-page-runtime-builder:latest'
- 'eu.gcr.io/$PROJECT_ID/space-page:latest'
- 'eu.gcr.io/$PROJECT_ID/space-page-app-builder:latest'
- 'eu.gcr.io/$PROJECT_ID/space-page-runtime-builder:latest'
- 'eu.gcr.io/$PROJECT_ID/main-page:latest'
- 'eu.gcr.io/$PROJECT_ID/main-page-app-builder:latest'
- 'eu.gcr.io/$PROJECT_ID/main-page-runtime-builder:latest'
```
